name: relation.py
on:
  push:
    branches:
      - main
    paths:
      - 'relation/relation.py'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'relation/relation.py'

jobs:      
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Install fonts
        run: sudo apt-get install ttf-wqy-microhei 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx matplotlib scipy
      - name: Generate graph
        run: |
          cd relation
          python relation.py save
      - name: Upload graph
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto generate relation graph by Workflow
